### ISSUE TITLE
Array of Array Products

### ISSUE THREAD

**Issue by andrewroblesdev** [andrewroblesdev/AlgoShell#8]
**Array of Array Products**

Given an array of integers arr, you’re asked to calculate for each index i the product of all integers except the integer at that index (i.e. except arr[i]). Implement a function arrayOfArrayProducts that takes an array of integers and returns an array of the products.

Solve without using division.

**Examples:**
input:  arr = [8, 10, 2]
output: [20, 16, 80] # by calculating: [10*2, 8*2, 8*10]

input:  arr = [2, 7, 3, 4]
output: [84, 24, 56, 42] # by calculating: [7*3*4, 2*3*4, 2*7*4, 2*7*3]

**Test Cases:**

Test Case 1
Input: [],Expected: []

Test Case 2
Input: [1],Expected: []

Test Case 3
Input: [2,2],Expected: [2,2]

Test Case 4
Input: [2,7,3,4],Expected: [84,24,56,42]

Test Case 5
Input: [2,3,0,982,10],Expected: [0,0,58920,0,0]

Test Case 6
Input: [-3,17,430,-6,5,-12,-11,5],Expected: [-144738000,25542000,1009800,-72369000,86842800,-36184500,-39474000,86842800]

**Comment by andrewroblesdev** [comment]
**Acceptance Criteria:**

-Add title, description, and examples to CodingQuestions.md
-Function is defined in solutions folder
-All test cases are implemented in test_solutions.py

Feel free to use existing questions as a reference!

When finished, please make a pull request to develop.

**Comment by andrewroblesdev** [comment]
Here is the correct solution to the problem that should pass the test cases:

```python
def array_of_array_products(arr):
  if len(arr) <= 1:
    return []
  
  rightProducts, leftProducts = calc_right_products(arr), calc_left_products(arr)
  
  return [left* right for left, right in zip(leftProducts, rightProducts)]
  
def calc_left_products(arr):
  product = 1
  productArr = [1] * len(arr)
  
  for i in range(len(arr)):

    productArr[i] = product
    product *= arr[i]
    
  return productArr

def calc_right_products(arr):
  product = 1
  productArr = [1] * len(arr)
  
  for i in reversed(range(len(arr))):
    productArr[i] = product
    product *= arr[i]
    
  return productArr
```

**Comment by mance-rah** [comment]
Tests ran, all passed. Updated and relevant files added to repo.
